languageCode = "en-us"
title = "FriS.de"
theme = "zen"

DefaultContentLanguage = "en"

[markup.goldmark.renderer]
  unsafe= true

[languages]
  [languages.en]
    weight = 1
    languageName = "EN"
    dateformat = ""

[params]
  copyright = "Â© 2020 Frieder Schrempf"
  #copyright = "This site is licensed under a <a href='https://creativecommons.org/licenses/by-sa/4.0/' target='_blank'>Creative Commons Attribution-ShareAlike 4.0 International License</a>."
  dateformat = ""            # Set the date format, default to "2 January, 2006"
  description = ""           # Set site description, used in meta tags and JSON-LD
  favicon = ""               # Relative path to favicon in json feed, no leading slash.
  feedlinks = false          # Show feed links in the footer.
  #footer = "A [example.org](https://example.org/) production."
  icon = ""                  # Relative path to icon in json feed, no leading slash.
  image = ""                 # Relative path to site image in JSON-LD, no leading slash.
  imageMaxWidth = ""         # Max width for images added via figure shortcode.
  jquery = true              # Add jQuery
  languageDir = ""           # Set ltr or rtl, defaults to ltr.
  logo = false               # Turn off the logo.
  menuShowHome = false       # Show the home page in the main menu
  microUsername = ""         # Your micro.blog username.
  mobileMenu = false         # Turn on a mobile menu on small screens.
  #piwikSiteId =              # Matamo site id
  #piwikTrackerUrl = ""       # Matamo url, schemaless and no slash on end (example.com/matamo).
  poweredby = true           # Show powered by hugo in footer
  search = false              # Site search with DuckDuckGo.
  searchSize = 20            # Search field size, default 20.
  sidebar = false             # Show a sidebar to the right
  submitted = true           # Show author and date information for a post.
